### ISSUE TITLE
Cannot find type definition file for 'webpack-dev-server' @5.1.0

### ISSUE THREAD

**Issue by byuji** [survivejs/webpack-merge#143]
After upgrading from 5.0.8 to 5.1.0 I got the following error:

```bash
$ tsc --noEmit
node_modules/webpack-merge/dist/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'webpack-dev-server'.

1 /// <reference types="webpack-dev-server" />
                        ~~~~~~~~~~~~~~~~~~


Found 1 error.
```

I reverted and it works fine. Running `yarn add @types/webpack-dev-server --dev` also fixes it.

Node version is v10.19.0, using macOS v10.15.6

**Comment by bebraw** [comment]
Thanks for the heads up. It should work without now. I'm not exactly sure how the build picked up the reference since there's no dependency on the type.

I made sure the development dependencies are up to date and now the result seems to be what's expected.
